version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: simple_bank_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
#    networks:
#      - local_net
#
#networks:
#  local_net:
#    driver: host